"""Write docs/DATA_AUDIT.md describing every OEWS file in data/ and cleaned_data/."""

from __future__ import annotations

import pandas as pd

from causal.oews_io import (
    ALIAS_TO_KEY,
    REPO_ROOT,
    SUPPRESSION_MARKERS,
    load_raw_year,
    raw_state_files,
)

KEY_FIELDS = ["ST", "AREA_TYPE", "OCC_CODE", "GROUP", "TOT_EMP", "H_MEAN", "A_MEAN",
              "H_MEDIAN", "A_MEDIAN", "H_PCT10", "A_PCT10"]
AUDIT_PATH = REPO_ROOT / "docs" / "DATA_AUDIT.md"


def original_name(raw_cols: list[str], key: str) -> str:
    """Return the year-specific column name that maps to a canonical key, or '-' if absent."""
    for c in raw_cols:
        if ALIAS_TO_KEY.get(str(c).strip().lower()) == key:
            return str(c)
    return "-"


def suppression_counts(df: pd.DataFrame) -> dict[str, int]:
    """Count cells equal to each suppression marker across the numeric fields."""
    cols = [c for c in KEY_FIELDS if c in df.columns and c not in ("ST", "AREA_TYPE", "OCC_CODE",
                                                                    "GROUP")]
    vals = df[cols].astype(str).apply(lambda s: s.str.strip())
    return {m: int((vals == m).sum().sum()) for m in SUPPRESSION_MARKERS}


def audit_raw() -> list[str]:
    """Audit the raw BLS workbooks in data/."""
    lines = ["## Raw BLS workbooks (`data/`)", "",
             "Suppression markers are counted over the numeric key fields. `*` means the wage "
             "estimate is not available, `**` means the employment estimate is not available, "
             "and `#` means the wage is at or above the top-coded value.", "",
             "| file | year | rows | " + " | ".join(KEY_FIELDS) + " | `*` | `**` | `#` |",
             "|" + "---|" * (len(KEY_FIELDS) + 6)]
    col_lists = []
    for year, path in raw_state_files().items():
        raw = pd.read_excel(path, dtype=str)
        df = load_raw_year(path)
        names = [original_name(list(raw.columns), k) for k in KEY_FIELDS]
        sup = suppression_counts(df)
        rel = path.relative_to(REPO_ROOT)
        lines.append(f"| `{rel}` | {year} | {len(raw)} | " + " | ".join(names)
                     + f" | {sup['*']} | {sup['**']} | {sup['#']} |")
        col_lists.append(f"- {year}: " + ", ".join(map(str, raw.columns)))
    lines += ["", "State code: 2019 has no state postal column (only `area` FIPS and "
              "`area_title`), so the causal pipeline keys every year on the `AREA` FIPS code.",
              "", "### Full column lists", ""] + col_lists
    return lines


def audit_cleaned() -> list[str]:
    """Audit the team's cleaned CSVs in cleaned_data/."""
    lines = ["", "## Team cleaned CSVs (`cleaned_data/`)", "",
             "| file | rows | columns | has `00-0000` All Occupations |", "|---|---|---|---|"]
    for p in sorted((REPO_ROOT / "cleaned_data").glob("*.csv")):
        df = pd.read_csv(p, dtype=str, low_memory=False)
        has_all = "OCC_CODE" in df.columns and (df["OCC_CODE"] == "00-0000").any()
        lines.append(f"| `{p.name}` | {len(df)} | {', '.join(df.columns)} | {has_all} |")
    lines += ["", "The cleaned CSVs drop the All Occupations (`00-0000`) rows, "
              "so the causal panel is built from the raw workbooks instead "
              "(see DECISIONS.md)."]
    return lines


def main() -> None:
    """Write the audit file (the panel builder appends a suppression-drop section later)."""
    lines = ["# Data audit", "", "Generated by `python -m causal.audit`.", ""]
    lines += audit_raw() + audit_cleaned()
    AUDIT_PATH.write_text("\n".join(lines) + "\n")
    print(f"wrote {AUDIT_PATH}")


if __name__ == "__main__":
    main()
