"""Build the state x year analysis panel (2005-2022) from raw OEWS files and minimum wages.

Output: data_processed/panel_state_year.parquet and .csv. A missing (suppressed) outcome is stored
as NaN and each estimator drops those state-years for that outcome only; counts are appended to
docs/DATA_AUDIT.md.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from causal.download_minwage import OUT_PATH as MW_PATH
from causal.geo import FIPS_TO_POSTAL, POSTAL_TO_DIVISION
from causal.oews_io import REPO_ROOT, load_raw_year, raw_state_files, to_numeric

PANEL_PARQUET = REPO_ROOT / "data_processed" / "panel_state_year.parquet"
PANEL_CSV = REPO_ROOT / "data_processed" / "panel_state_year.csv"
AUDIT_PATH = REPO_ROOT / "docs" / "DATA_AUDIT.md"
YEARS = range(2005, 2023)

# outcome name -> (OCC_CODE, hourly column, annual fallback column or None)
OUTCOMES: dict[str, tuple[str, str, str | None]] = {
    "log_p10_all": ("00-0000", "H_PCT10", "A_PCT10"),
    "log_emp_food": ("35-0000", "TOT_EMP", None),
    "log_median_food": ("35-0000", "H_MEDIAN", "A_MEDIAN"),
    "log_median_cs": ("15-0000", "H_MEDIAN", "A_MEDIAN"),
    "log_emp_all": ("00-0000", "TOT_EMP", None),
}
HOURS_PER_YEAR = 2080


def extract_year(year: int) -> tuple[pd.DataFrame, list[dict]]:
    """Return one row per state for a year with level outcomes, plus a log of annual fallbacks."""
    df = load_raw_year(raw_state_files()[year])
    df["fips"] = pd.to_numeric(df["AREA"], errors="coerce")
    df = df[df["fips"].isin(FIPS_TO_POSTAL)]
    rows: dict[int, dict] = {int(f): {"fips": int(f), "year": year} for f in df["fips"].unique()}
    fallbacks: list[dict] = []
    for name, (occ, col, alt) in OUTCOMES.items():
        sub = df[df["OCC_CODE"].str.strip() == occ].set_index("fips")
        values = to_numeric(sub[col])
        if alt is not None:
            annual = to_numeric(sub[alt]) / HOURS_PER_YEAR
            used = values.isna() & annual.notna()
            fallbacks += [{"outcome": name, "year": year, "fips": int(f)}
                          for f in used[used].index]
            values = values.fillna(annual)
        for f, v in values.items():
            rows[int(f)][name] = v
    return pd.DataFrame(rows.values()), fallbacks


def build() -> tuple[pd.DataFrame, pd.DataFrame]:
    """Assemble the panel. Returns (panel, annual-fallback log)."""
    parts, fb = [], []
    for y in YEARS:
        part, f = extract_year(y)
        parts.append(part)
        fb += f
    levels = pd.concat(parts, ignore_index=True)
    panel = levels.copy()
    for name in OUTCOMES:
        panel[name] = np.log(levels[name].where(levels[name] > 0))
    mw = pd.read_csv(MW_PATH)[["fips", "year", "effective_mw"]]
    panel = panel.merge(mw, on=["fips", "year"], how="inner", validate="one_to_one")
    panel["state"] = panel["fips"].map(FIPS_TO_POSTAL)
    panel["division"] = panel["state"].map(POSTAL_TO_DIVISION)
    panel["log_mw"] = np.log(panel["effective_mw"])
    cols = ["state", "fips", "division", "year", "effective_mw", "log_mw", *OUTCOMES]
    return panel[cols].sort_values(["state", "year"]).reset_index(drop=True), pd.DataFrame(fb)


def write_audit(panel: pd.DataFrame, fallbacks: pd.DataFrame) -> None:
    """Append (or replace) the suppression section of docs/DATA_AUDIT.md."""
    marker = "## Panel suppression and drops"
    text = AUDIT_PATH.read_text().split(marker)[0].rstrip()
    lines = [marker, "", "Generated by `python -m causal.build_panel`. State-years where an outcome "
             "is suppressed or missing are dropped for that outcome only.", "",
             "| outcome | state-years available | dropped (suppressed or missing) |",
             "|---|---|---|"]
    for name in OUTCOMES:
        lines.append(f"| {name} | {int(panel[name].notna().sum())} | "
                     f"{int(panel[name].isna().sum())} |")
    n_fb = 0 if fallbacks.empty else len(fallbacks)
    lines += ["", f"Hourly values replaced by annual / 2080: {n_fb} state-years."]
    if n_fb:
        lines += ["", fallbacks.to_markdown(index=False)]
    AUDIT_PATH.write_text(text + "\n\n" + "\n".join(lines) + "\n")


def main() -> None:
    panel, fallbacks = build()
    PANEL_PARQUET.parent.mkdir(parents=True, exist_ok=True)
    panel.to_parquet(PANEL_PARQUET, index=False)
    panel.to_csv(PANEL_CSV, index=False)
    write_audit(panel, fallbacks)
    print(f"wrote {PANEL_PARQUET} ({len(panel)} rows)")
    print(panel[list(OUTCOMES)].notna().sum().to_string())


if __name__ == "__main__":
    main()
