"""Exploratory figures, descriptive statistics, and docs/EDA.md."""

from __future__ import annotations

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

from causal.build_panel import OUTCOMES, PANEL_PARQUET  # noqa: E402
from causal.oews_io import REPO_ROOT  # noqa: E402
from causal.treatment import load_treatment  # noqa: E402

FIG_DIR = REPO_ROOT / "results" / "figures"
DESC_PATH = REPO_ROOT / "results" / "descriptives.csv"
EDA_DOC = REPO_ROOT / "docs" / "EDA.md"


def plot_mw_2005_2022(panel: pd.DataFrame) -> str:
    """Bar chart of each state's effective minimum wage in 2005 and 2022."""
    w = panel.pivot(index="state", columns="year", values="effective_mw")[[2005, 2022]]
    w = w.sort_values(2022)
    fig, ax = plt.subplots(figsize=(14, 5))
    x = range(len(w))
    ax.bar([i - 0.2 for i in x], w[2005], width=0.4, label="2005", color="#9aa5b1")
    ax.bar([i + 0.2 for i in x], w[2022], width=0.4, label="2022", color="#1f6feb")
    ax.axhline(7.25, color="black", lw=0.8, ls="--", label="Federal $7.25 (2009+)")
    ax.set_xticks(list(x), w.index, rotation=90, fontsize=8)
    ax.set_ylabel("Effective minimum wage ($/hour, annual average)")
    ax.set_title("Effective minimum wage by state, 2005 vs 2022")
    ax.legend()
    fig.tight_layout()
    name = "mw_2005_vs_2022.png"
    fig.savefig(FIG_DIR / name, dpi=150)
    plt.close(fig)
    return name


def plot_p10_by_group(panel: pd.DataFrame, treat: pd.DataFrame) -> str:
    """Mean log 10th percentile wage for never-treated vs treated states over time."""
    df = panel.merge(treat[["state", "group"]], on="state")
    df = df[df["group"] != "dropped"]
    means = df.groupby(["year", "group"])["log_p10_all"].mean().unstack()
    fig, ax = plt.subplots(figsize=(8, 5))
    labels = {"never_treated": "Stayed at federal minimum", "treated": "Raised minimum (2011+)"}
    for col in means:
        ax.plot(means.index, means[col], marker="o", label=labels[col])
    ax.set_ylabel("Mean log 10th percentile hourly wage (all occupations)")
    ax.set_xlabel("OEWS reference year (May)")
    ax.set_xticks(list(means.index[::2]))
    ax.set_title("Low-end wages: states that raised the minimum vs states that did not")
    ax.legend()
    fig.tight_layout()
    name = "p10_by_group.png"
    fig.savefig(FIG_DIR / name, dpi=150)
    plt.close(fig)
    return name


def main() -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    panel = pd.read_parquet(PANEL_PARQUET)
    treat = load_treatment()
    f1 = plot_mw_2005_2022(panel)
    f2 = plot_p10_by_group(panel, treat)
    desc = panel[["effective_mw", "log_mw", *OUTCOMES]].describe().T
    desc.to_csv(DESC_PATH)
    counts = treat["group"].value_counts()
    cohorts = treat.dropna(subset=["g"]).groupby("g")["state"].apply(", ".join)
    lines = ["# Exploratory analysis", "", "Generated by `python -m causal.eda`.", "",
             f"![Minimum wage 2005 vs 2022](../results/figures/{f1})", "",
             f"![Low-end wages by group](../results/figures/{f2})", "",
             "## Treatment groups", "",
             f"- Treated states: {counts.get('treated', 0)}",
             f"- Never-treated states: {counts.get('never_treated', 0)}",
             f"- Dropped states: {counts.get('dropped', 0)} "
             f"({', '.join(treat.loc[treat['group'] == 'dropped', 'state'])})", "",
             "| treatment year g | states |", "|---|---|"]
    lines += [f"| {g} | {s} |" for g, s in cohorts.items()]
    lines += ["", "Note: the gap between the groups narrows from 2005 to 2010, when the federal "
              "minimum rose from $5.15 to $7.25 and bound mostly in the never-treated states. "
              "Pre-2010 years enter the event study only as far leads, so the pre-trend test "
              "is the main check on this.", "", "## Descriptive statistics", "",
              desc.round(4).to_markdown()]
    EDA_DOC.write_text("\n".join(lines) + "\n")
    print(f"wrote {EDA_DOC}, {f1}, {f2}, {DESC_PATH.name}")


if __name__ == "__main__":
    main()
