"""Generate docs/LEARNING_NOTES.md. Concepts are fixed text; every number comes from results/."""

from __future__ import annotations

from causal.oews_io import REPO_ROOT
from causal.report import f3, fp, load, pct, twfe_row
from causal.treatment import load_treatment

OUT = REPO_ROOT / "docs" / "LEARNING_NOTES.md"

CONCEPTS = """# Learning notes

_Generated by `python -m causal.learning_notes`. Numbers are read from `results/*.json`, the same
source as [RESULTS.md](../RESULTS.md)._

These notes explain every method in plain English so you can defend each line of the project.

## 1. What difference-in-differences (DiD) estimates

DiD compares how an outcome changed in states that raised the minimum wage with how it changed in
states that did not. The first difference (after minus before) removes anything fixed about a
state, such as Massachusetts always paying more than Mississippi. The second difference (treated
change minus control change) removes shocks that hit every state in the same year, such as a
national recession. What is left is the effect of the policy, **if** the treated states would have
followed the same path as the controls without the policy. That is the **parallel trends
assumption**. It cannot be tested directly after treatment, but it can be checked before treatment:
if treated and control states were already drifting apart before the increase (non-zero "leads" in
the event study), the assumption is in doubt.

## 2. Why TWFE can be biased with staggered timing, and what Callaway and Sant'Anna fix

A two-way fixed effects (TWFE) regression with state and year fixed effects is the classic way to
run DiD with many states and years. When states adopt at different times and the effect changes
over time, Goodman-Bacon (2021) showed that TWFE quietly uses already-treated states as controls
for later-treated ones. If the early states' effect is still growing, that comparison subtracts
part of the real effect, and some comparisons can even get negative weight. Callaway and Sant'Anna
(2021) avoid this by building every comparison explicitly: for each cohort g (states first treated
in year g) and each year t, they compute a clean 2x2 DiD against never-treated states only, using
year g - 1 as the baseline. Those ATT(g, t) pieces are then averaged by event time or into one
overall effect, with weights you choose (here, cohort size). No already-treated state is ever used
as a control.

## 3. How synthetic control picks weights, and why the placebo test gives a p-value

Instead of comparing one treated state with the average of all controls, synthetic control builds a
weighted average of control states ("synthetic Arizona") that matches the treated state's outcome
path and predictors **before** the policy. Weights are non-negative and sum to one, so the
synthetic state is an interpolation of real states, not an extrapolation. After the policy, the gap
between the real and synthetic state is the estimated effect. With one treated unit there is no
standard error, so inference is done by permutation: pretend each control state was treated, refit,
and see how its gap compares. The statistic is post-period RMSPE divided by pre-period RMSPE (a
large post gap only counts if the pre-period fit was good). If the real treated state has the
largest ratio among N units, the p-value is 1/N: the chance of getting a ratio that extreme by
randomly picking which state to call treated.

## 4. How the power simulation works and what MDE means

Power is the probability of detecting an effect that is really there. The simulation takes only
never-treated states, where the true effect of a minimum wage increase is zero, assigns fake
treatment years at random, adds a known effect delta to the fake-treated outcomes, and runs the
DiD. Repeating that 500 times for each delta gives the share of runs with p < 0.05. At delta = 0
that share is the false positive rate (it should be near 5%). The **minimum detectable effect
(MDE)** is the smallest delta found 80% of the time. If the MDE is larger than plausible true
effects, a null result says little: the study may simply be too small to see them.

## 5. What OEWS three-year pooling does to the results

Each May OEWS estimate combines six semiannual survey panels collected over three years. So the
"2017" estimate for Arizona partly reflects survey responses from 2014-2016, before Arizona's
increase. This smooths year-to-year changes, pulls estimated effects toward zero, and spreads an
immediate effect over two to three years in the event study. That is why the analysis reads effects
over several post-treatment years, adds lagged-treatment regressions, and treats estimated effects
as conservative.
"""


def main() -> None:
    twfe, es, synth, power = load()
    treat = load_treatment()
    o = es["outcomes"]
    p10 = o["log_p10_all"]
    food_w = o["log_median_food"]
    emp = o["log_emp_food"]
    cs_p10 = p10["callaway_santanna"]["overall_att"]
    cs_fw = food_w["callaway_santanna"]["overall_att"]
    cs_emp = emp["callaway_santanna"]["overall_att"]
    pc_emp = emp["cs_pre_covid"]
    pc_p10 = p10["cs_pre_covid"]
    el_emp = twfe_row(twfe, "log_emp_food")
    el_emp_ctl = twfe_row(twfe, "log_emp_food", "control_log_emp_all")
    el_emp_div = twfe_row(twfe, "log_emp_food", "division_x_year_fe")
    pl = power["placebo_outcome"]
    pl_cs = o["log_median_cs"]["callaway_santanna"]["overall_att"]
    pl_base = twfe_row(twfe, "log_median_cs")
    pl_div = twfe_row(twfe, "log_median_cs", "division_x_year_fe")
    counts = treat["group"].value_counts()
    dropped = ", ".join(treat.loc[treat["group"] == "dropped", "state"])
    top_w = sorted(synth["weights"].items(), key=lambda kv: -kv[1])[:3]
    top_w_txt = ", ".join(f"{k} ({v:.2f})" for k, v in top_w)
    mde_emp = power["outcomes"]["log_emp_food"]["mde_80"]
    mde_p10 = power["outcomes"]["log_p10_all"]["mde_80"]
    fpr_emp = power["outcomes"]["log_emp_food"]["false_positive_rate"]
    fpr_p10 = power["outcomes"]["log_p10_all"]["false_positive_rate"]
    bin_p10 = p10["binary_twfe"]
    lead_max = max(abs(c["estimate"]) for c in p10["callaway_santanna"]["coefficients"]
                   if c["e"] < -1)

    qa = [
        ("What is the headline finding?",
         f"Large state minimum wage increases raised the 10th percentile hourly wage by about "
         f"{pct(cs_p10['estimate'])} ({f3(cs_p10['estimate'])} log points, 95% CI "
         f"[{f3(cs_p10['ci_low'])}, {f3(cs_p10['ci_high'])}]) relative to states that stayed at "
         f"$7.25, and food-service median wages by {f3(cs_fw['estimate'])} log points. I do not "
         f"find robust evidence of food-service job losses: the full-sample estimate is "
         f"{f3(cs_emp['estimate'])} (p {fp(cs_emp['p_value'])}) but it goes to "
         f"{f3(pc_emp['estimate'])} (p {fp(pc_emp['p_value'])}) once the pandemic years are "
         f"excluded."),
        ("How did you define treatment, and why drop some states?",
         f"A state is treated in the first year from 2011 on that its effective minimum rose by "
         f"at least $0.75 and 8%; never-treated states sat at $7.25 every year from 2010 to 2022. "
         f"That gives {counts.get('treated', 0)} treated and {counts.get('never_treated', 0)} "
         f"never-treated states. {counts.get('dropped', 0)} states ({dropped}) were already "
         f"above the federal minimum by 2010 and never had a single-year jump big enough to "
         f"count, so they have no clean before-and-after and are left out of the event study, "
         f"though they stay in the continuous regressions."),
        ("Why not just run a two-way fixed effects regression?",
         f"With staggered adoption TWFE uses already-treated states as controls, which can bias "
         f"the estimate when effects grow over time (Goodman-Bacon 2021). Here the static binary "
         f"TWFE gives {f3(bin_p10['estimate'])} for the 10th percentile wage while "
         f"Callaway-Sant'Anna gives {f3(cs_p10['estimate'])}"
         + (", which is the direction you expect when growing effects contaminate the TWFE "
            "comparisons" if bin_p10["estimate"] < cs_p10["estimate"] else "")
         + ". I report both, and my own CS "
         "implementation matches the `differences` package to machine precision."),
        ("The pre-trend test fails for the wage outcomes. How do you handle that?",
         f"I report it rather than hide it: the CS pre-trend p-value is "
         f"{fp(p10['callaway_santanna']['pretrend']['p_value'])} for the 10th percentile wage and "
         f"{fp(food_w['callaway_santanna']['pretrend']['p_value'])} for food-service median "
         f"wages. The leads are small, the largest is {f3(lead_max)} against a post effect of "
         f"{f3(cs_p10['estimate'])}, and the jump starts right at event time 0. The synthetic "
         f"control, which matches Arizona's pre-period path almost exactly, gives the same sign. "
         f"So I treat the direction as solid and the exact size as approximate."),
        ("Did the minimum wage cost food-service jobs?",
         f"The evidence does not support a robust job loss. The continuous TWFE elasticity is "
         f"{f3(el_emp['estimate'])} (p {fp(el_emp['p_value'])}) and "
         f"{f3(el_emp_div['estimate'])} (p {fp(el_emp_div['p_value'])}) with division-by-year "
         f"effects. Controlling for total employment gives {f3(el_emp_ctl['estimate'])} "
         f"(p {fp(el_emp_ctl['p_value'])}), which is the one specification I would flag as "
         f"pointing toward a loss in food's share of jobs. The CS estimate is "
         f"{f3(cs_emp['estimate'])} but falls to {f3(pc_emp['estimate'])} before COVID, and the "
         f"employment leads pass the pre-trend test."),
        ("Why does the pre-COVID check matter?",
         f"For the 2014-2017 cohorts, event times +4 and +5 land in 2019-2022, when pandemic "
         f"restrictions hit food service very differently across states. Ending the sample in "
         f"2019 removes that overlap. Food employment moves from "
         f"{f3(cs_emp['estimate'])} to {f3(pc_emp['estimate'])}, while the 10th percentile wage "
         f"effect stays clearly positive ({f3(pc_p10['estimate'])}), so the wage result is not a "
         f"pandemic artifact but the employment result may be."),
        ("Walk me through the synthetic control.",
         f"The code picks the treated state with the biggest jump, which is "
         f"{synth['case_state']}: +${synth['jump_usd']:.2f} ({100 * synth['jump_pct']:.0f}%) in "
         f"{synth['treatment_year']}. The largest weights in synthetic {synth['case_state']} are "
         f"{top_w_txt}, with "
         f"a pre-period RMSPE of {synth['pre_rmspe']:.4f}, and the post-period gap averages "
         f"{f3(synth['avg_post_gap'])} log points. {synth['case_state']} ranks {synth['rank']} "
         f"of {synth['n_units']} in the post/pre RMSPE ratio, so the permutation p-value is "
         f"{fp(synth['permutation_p_value'])}, which is the smallest p-value possible with "
         f"{synth['n_units']} units."),
        ("How much power does the design have?",
         f"In 500 placebo simulations the false positive rate was {fpr_emp:.3f} for food "
         f"employment and {fpr_p10:.3f} for the 10th percentile wage, close to the nominal 5%. The "
         f"minimum detectable effect at 80% power is {f3(mde_emp)} log points for food employment "
         f"and {f3(mde_p10)} for the wage. "
         + ("So the wage effect is above what the design can reliably detect, but "
            if cs_p10["estimate"] > mde_p10 else "So even the wage effect is near the limit, and ")
         + f"food employment effects smaller than about {f3(mde_emp)} could easily be "
         f"missed. That is why I call the employment result 'not robustly different from zero', "
         f"not 'zero'."),
        ("What did the placebo outcome show?",
         f"Computer and math median wages should not react to the minimum wage. In the event-study "
         f"designs they do not (CS {f3(pl_cs['estimate'])}, p {fp(pl_cs['p_value'])}), but the "
         f"baseline continuous TWFE finds {f3(pl_base['estimate'])} (p {fp(pl_base['p_value'])}). "
         f"That disappears with division-by-year fixed effects ({f3(pl_div['estimate'])}, p "
         f"{fp(pl_div['p_value'])}). Overall {pl['n_significant_at_5pct']} of "
         f"{pl['n_estimates']} placebo estimates are significant, which tells me the simple "
         f"continuous TWFE partly picks up regional wage growth and is the weakest design here."),
        ("What are the main limitations, and what would you do next?",
         "OEWS pools three years of surveys, so effects are smoothed and biased toward zero; the "
         "data are state averages, so city minimums and within-state differences are lost; and "
         "states chose their own policies. Next I would use county-level QCEW employment with a "
         "contiguous border-county design, which compares neighboring counties across state "
         "lines, and CPS microdata to look at hours and teen employment directly."),
    ]
    lines = [CONCEPTS, "## 6. Ten likely interview questions", ""]
    for i, (q, a) in enumerate(qa, 1):
        lines += [f"**{i}. {q}**", "", a, ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
